language: java
jdk:
- oraclejdk8
after_success:
  mvn clean cobertura:cobertura coveralls:report -DrepoToken=$repo_token
env:
  global:
    secure: PggG+RFh6A41MqgVDQ1tbttuDqtFcYqU5/PjPAbu+LcnQHLhZ7oQB+PgBWqw+BXdOJlRoW5MEVVznCnw9VMUuL5E9mgJvy/xudZWGZSSuuPQKfgy44/YOo5/9sIpuOafQAyhxKVTJ8wMmslErrmXpnTnEB82PqrHYU3hXkaRyss/Ee67++Y8oD+ZPj/zOj2d9fwM7imWUF0EsPLTiGpiHI/ufRS55i+EfQLTXgWfPCH2CQaZEd7m59dH7p9RCRQV4lf7RRq80DnP+imsKYYfOXZOmEUSMV3j5HNkYdaNoERutqBo1VBbos1+HdNjUuNvPg8ien8xLUJig5YTr6PIlCsuCH5LCZRwc87FzYb7YVhlqRz9dKYOdcbMHPL3NvouKO9rJsferoItgRS3esDNL7+KuTiCGSW8qpT/an/StKlivl2ujMNUszS1Iitdv8pOEkC2awlBY3tyFyXQmsm5KlZ9LbpBnwjfM7fyrGyxeOS4DEkL7o822dy9RPc3/fKLQxNYHjpdAIblzO5wUUIbHp70XVDxMfmkEIr3ubJdTJJg2fxAgchwAi+YsQ+VbGNoOwmtMl64s3fLsbU2CxZo38lMg9MZYk/a6eP1WXIOXj1PYCNptPYQ1kAYbpesPSuGb2LzSAzRnbQt9i9K3bcA4A/SuSAx4aMo7k28Zf624Bs=
